version: '3'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: k6
      INFLUXDB_USER_PASSWORD: k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  k6:
    image: loadimpact/k6:latest
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    entrypoint: [ "sh", "-c", "while true; do sleep 30; done;" ]

  k6_runner:
    image: loadimpact/k6:latest
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "k6", "run", "--out", "influxdb=http://influxdb:8086/k6", "/scripts/script.js" ]
    depends_on:
      - influxdb
